const express = require('express');
const path = require('path');
const app = express();
const port = process.argv.slice(2).pop() || process.env.port || 4000;
const sockets = require('./sockets.js');
app.use(require('./middleware/sendStatusMessage.js'));
app.use(express.static(__dirname+'/public'));
app.use(require('body-parser').json());
app.get('/mediautils.js', (req, res) => res.sendFile(path.resolve('../../dist/mediautils.js')));
sockets.bind(app.listen(port, () => console.log('http://127.0.0.1:'+port+'/')));